version: "3.9"

services:
  go_app:
    container_name: go_app
    image: go-api
    build: .
    env_file:
      - .env.docker
    ports:
      - 8000:8000
    depends_on:
      - go_db

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}
